# Generated by Django 4.1.3 on 2022-11-14 11:04

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='username')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='phone')),
                ('photo', models.FilePathField(path=pathlib.PurePosixPath('/Users/sv/PycharmProjects/pythonProject/django-telegram/media/photo'))),
                ('is_bot', models.BooleanField(default=False, verbose_name='is bot')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('groups', models.ManyToManyField(related_name='users', to='app_telegram.telegramchat')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, db_index=True, default='', null=True, verbose_name='message')),
                ('from_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.telegramchat')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chats', to='app_telegram.telegramuser'),
        ),
    ]
