# Generated by Django 4.1.3 on 2022-11-14 11:48

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='photo',
            field=models.FilePathField(null=True, path=pathlib.PurePosixPath('/Users/sv/PycharmProjects/pythonProject/django-telegram/media/photo')),
        ),
    ]
